const て = [
["おきます","thức dậy","おきて","okite"],
["やすみます","","やすんで","yasunde"],
["はたらきます","","はたらいて","hataraite"],
["勉強します","","const て = [
["おきます","thức dậy","おきて","okite"],
["やすみます","","やすんで","yasunde"],
["はたらきます","","はたらいて","hataraite"],
["勉強します","","べんきょうして","benkyoushite"],
["かいます","","かって","katte"],
["のみます","","のんで","nonde"],
["すいます","","すって","sutte"],
["みます","","みて","mite"],
["ききます","","きいて","kiite"],
["散歩します","","さんぽして","sanposhite"],
["かきます","","かいて","kaite"],
["とります","","とって","totte"],
["あいます","","あって","atte"],
["します","","して","shite"],
["きります","","きって","kitte"],
["おくります","","おくって","okutte"],
["あげます","","あげて","agete"],
["もらいます","","もらって","moratte"],
["かします","","かして","kashite"],
["きます","đến","きて","kite"],
["食事します","","しょくじして","shokujishite"],
["おしえます","","おしえて","oshiete"],
["ならいます","","ならって","naratte"],
["かけます","","かけて","kakete"],
["かえります","","かえって","kaette"],
["わかります","","わかって","wakatte"],
["あります","","あって","atte"],
["います","","いて","ite"],
["出張します","","しゅっちょうして","shutchoushite"],
["あそびます","","あそんで","asonde"],
["うります","","うって","utte"],
["しります","","しって","shitte"],
["すみます","","すんで","sunde"],
["研究します","","けんきゅうして","kenkyuushite"],
["のります","","のって","notte"],
["おります","","おりて","orite"],
["のりかえます","","のりかえて","norikaete"],
["あびます","","あびて","abite"],
["残業します","","ざんぎょうして","zangyoushite"],
["わすれます","","わすれて","wasurete"],
["なくします","","なくして","nakushite"],
["はらいます","","はらって","haratte"],
["かえします","","かえして","kaeshite"],
["予約します","","よやくして","yoyakushite"],
["あらいます","","あらって","aratte"],
["ひきます","","ひいて","hiite"],
["うたいます","","うたって","utatte"],
["あつめます","","あつめて","atsumete"],
["すてます","","すてて","sutete"],
["かえます","","かえて","kaete"],
["いそぎます","","いそいで","isoide"],
["しらべます","","しらべて","shirabete"],
["修理します","","しゅうりして","shuurishite"],
["おもいます","","おもって","omotte"],
["いいます","","いって","itte"],
["かちます","","かって","katte"],
["まけます","","まけて","makete"],
["役に立ちます","","やくにたって","yakunitatte"],
["うごきます","","うごいて","ugoite"],
["やめます","","やめて","yamete"],
["きをつけます","","きをつけて","kiwotsukete"],
["留学します","","りゅうがくして","ryuugakushite"],
["はきます","","はいて","haite"],
["かぶります","","かぶって","kabutte"],
["うまれます","","うまれて","umarete"],
["まわします","","まわして","mawashite"],
["およぎます","","およいで","oyoide"],
["むかえます","","むかえて","mukaete"],
["きます","mặc","きて","kite"],
["つかれます","","つかれて","tsukarete"],
["結婚します","","けっこんして","kekkonshite"],
["買い物します","","かいものして","kaimonoshite"],
["たべます","","たべて","tabete"],
["かります","","かりて","karite"],
["はなします","","はなして","hanashite"],
["はいります","","はいって","haitte"],
["つけます","","つけて","tsukete"],
["あけます","","あけて","akete"],
["けします","","けして","keshite"],
["しめます","","しめて","shimete"],
["のぼります","","のぼって","nobotte"],
["まちます","","まって","matte"],
["てつだいます","","てつだって","tetsudatte"],
["つかいます","","つかって","tsukatte"],
["みせます","","みせて","misete"],
["すわります","","すわって","suwatte"],
["ねます","","ねて","nete"],
["たちます","","たって","tatte"],
["でます","","でて","dete"],
["ふります","","ふって","futte"],
["コピーします","","コピーして","kopishite"],
["つくります","","つくって","tsukutte"],
["おわります","","おわって","owatte"],
["とまります","","とまって","tomatte"],
["いれます","","いれて","irete"],
["だします","","だして","dashite"],
["おろします","","おろして","oroshite"],
["おします","","おして","oshite"],
["はじめます","","はじめて","hajimete"],
["見学します","","けんがくして","kengakushite"],
["電話します","","でんわして","denwashite"],
["でかけます","","でかけて","dekakete"],
["ぬぎます","","ぬいで","nuide"],
["もっていきます","","もっていって","motteitte"],
["心配します","","しんぱいして","shinpaishite"],
["おぼえます","","おぼえて","oboete"],
["かかります","","かかって","kakatte"],
["おきます","đặt, để","おいて","oite"],
["洗濯します","","せんたくして","sentakushite"],
["なります","","なって","natte"],
["練習します","","れんしゅうして","renshuushite"],
["運転します","","うんてんして","untenshite"],
["できます","","できて","dekite"],
["いります","","いって","itte"],
["掃除します","","そうじして","soujishite"],
["さわります","","さわって","sawatte"],
["あるきます","","あるいて","aruite"],
["わたします","","わたして","watashite"],
["くれます","","くれて","kurete"],
["なおします","","なおして","naoshite"],
["つれてきます","","つれてきて","tsuretekite"],
["案内します","","あんないして","annaishite"],
["かんがえます","","かんがえて","kangaete"],
["つきます","","ついて","tsuite"],
["たります","","たりて","tarite"],
["説明します","","せつめいして","setsumeishite"],
["がんばります","","がんばって","ganbatte"],
["かえます","","かえて","kaete"],
["まがります","","まがって","magatte"],
["つれていきます","","つれていって","tsureteitte"]
];

const HIRAGANA = {
  gojuon: [
    ["あ","a"],["い","i"],["う","u"],["え","e"],["お","o"],
    ["か","ka"],["き","ki"],["く","ku"],["け","ke"],["こ","ko"],
    ["さ","sa"],["し",["shi","si"]],["す","su"],["せ","se"],["そ","so"],
    ["た","ta"],["ち",["chi","ti"]],["つ",["tsu","tu"]],["て","te"],["と","to"],
    ["な","na"],["に","ni"],["ぬ","nu"],["ね","ne"],["の","no"],
    ["は","ha"],["ひ","hi"],["ふ",["fu","hu"]],["へ","he"],["ほ","ho"],
    ["ま","ma"],["み","mi"],["む","mu"],["め","me"],["も","mo"],
    ["や","ya"],["ゆ","yu"],["よ","yo"],
    ["ら","ra"],["り","ri"],["る","ru"],["れ","re"],["ろ","ro"],
    ["わ","wa"],["を",["wo","o"]],
    ["ん","n"]
  ],
  dakuten: [
    ["が","ga"],["ぎ","gi"],["ぐ","gu"],["げ","ge"],["ご","go"],
    ["ざ","za"],["じ",["ji","zi"]],["ず","zu"],["ぜ","ze"],["ぞ","zo"],
    ["だ","da"],["ぢ",["ji","di"]],["づ",["zu","du"]],["で","de"],["ど","do"],
    ["ば","ba"],["び","bi"],["ぶ","bu"],["べ","be"],["ぼ","bo"],
    ["ぱ","pa"],["ぴ","pi"],["ぷ","pu"],["ぺ","pe"],["ぽ","po"]
  ],
  yoon: [
    ["きゃ","kya"],["きゅ","kyu"],["きょ","kyo"],
    ["しゃ",["sha","sya"]],["しゅ",["shu","syu"]],["しょ",["sho","syo"]],
    ["ちゃ",["cha","tya"]],["ちゅ",["chu","tyu"]],["ちょ",["cho","tyo"]],
    ["にゃ","nya"],["にゅ","nyu"],["にょ","nyo"],
    ["ひゃ","hya"],["ひゅ","hyu"],["ひょ","hyo"],
    ["みゃ","mya"],["みゅ","myu"],["みょ","myo"],
    ["りゃ","rya"],["りゅ","ryu"],["りょ","ryo"],
    ["ぎゃ","gya"],["ぎゅ","gyu"],["ぎょ","gyo"],
    ["じゃ",["ja","zya"]],["じゅ",["ju","zyu"]],["じょ",["jo","zyo"]],
    ["びゃ","bya"],["びゅ","byu"],["びょ","byo"],
    ["ぴゃ","pya"],["ぴゅ","pyu"],["ぴょ","pyo"]
  ],
  vidu: [
    ["あい","ai","tình yêu"],["あさ","asa","buổi sáng"],["あめ","ame","mưa"],
    ["いえ","ie","nhà"],["いす","isu","cái ghế"],["いぬ","inu","con chó"],
    ["うた","uta","bài hát"],["うみ","umi","biển"],["えき","eki","nhà ga"],
    ["おかね","okane","tiền"],["おちゃ","ocha","trà"],["おとこ","otoko","đàn ông"],
    ["おんな","onna","phụ nữ"],["かお","kao","khuôn mặt"],["かさ","kasa","cái ô"],
    ["かぜ","kaze","gió (cảm cúm)"],["かみ","kami","tóc (giấy)"],["き","ki","cây"],
    ["くつ","kutsu","giày"],["くも","kumo","mây"],["くるま","kuruma","xe hơi"],
    ["こえ","koe","giọng nói"],["ことば","kotoba","từ ngữ"],["さかな","sakana","con cá"],
    ["さくら","sakura","hoa anh đào"],["しお","shio","muối"],["しま","shima","hòn đảo"],
    ["すし","sushi","sushi"],["たまご","tamago","quả trứng"],["ちから","chikara","sức mạnh"],
    ["つき","tsuki","mặt trăng"],["とけい","tokei","đồng hồ"],["とり","tori","con chim"],
    ["なつ","natsu","mùa hè"],["にく","niku","thịt"],["ねこ","neko","con mèo"],
    ["はな","hana","hoa"],["はる","haru","mùa xuân"],["ひと","hito","con người"],
    ["ふゆ","fuyu","mùa đông"],["ほし","hoshi","ngôi sao"],["まち","machi","thị trấn"],
    ["みず","mizu","nước"],["みみ","mimi","lỗ tai"],["むし","mushi","côn trùng"],
    ["め","me","con mắt"],["やま","yama","núi"],["ゆき","yuki","tuyết"],
    ["よる","yoru","ban đêm"],["わたし","watashi","tôi"],
    ["あたま","atama","đầu"],["あに","ani","anh trai"],["あね","ane","chị gái"],
    ["いもうと","imouto","em gái"],["おとうと","otouto","em trai"],["ちち","chichi","bố"],
    ["はは","haha","mẹ"],["そふ","sofu","ông"],["そぼ","sobo","bà"],
    ["かぞく","kazoku","gia đình"],["ともだち","tomodachi","bạn bè"],["せんせい","sensei","giáo viên"],
    ["がくせい","gakusei","học sinh"],["かいしゃ","kaisha","công ty"],["しごと","shigoto","công việc"],
    ["でんわ","denwa","điện thoại"],["てがみ","tegami","lá thư"],["きっぷ","kippu","vé xe/tàu"],
    ["えいが","eiga","phim điện ảnh"],["おんがく","ongaku","âm nhạc"],["しゃしん","shashin","ảnh chụp"],
    ["にわ","niwa","sân vườn"],["へや","heya","căn phòng"],["まど","mado","cửa sổ"],
    ["とびら","tobira","cánh cửa"],["かぎ","kagi","chìa khóa"],["はし","hashi","đôi đũa"],
    ["さら","sara","cái đĩa"],["ちゃわん","chawan","cái bát cơm"],["たべもの","tabemono","đồ ăn"],
    ["のみもの","nomimono","đồ uống"],["やさい","yasai","rau củ"],["くだもの","kudamono","trái cây"],
    ["にわとり","niwatori","con gà"],["うし","ushi","con bò"],["うま","uma","con ngựa"],
    ["ぶた","buta","con lợn"],["ひつじ","hitsuji","con cừu"],["さる","saru","con khỉ"],
    ["かえる","kaeru","con ếch"],["ちょう","chou","con bướm"],["はち","hachi","con ong"],
    ["くさ","kusa","cỏ"],["こおり","koori","nước đá"],["ゆびわ","yubiwa","nhẫn đeo tay"],
    ["ぼうし","boushi","mũ nón"],["くつした","kutsushita","vớ/tất"],["めがね","megane","kính mắt"],
    ["かばん","kaban","cái cặp"],["つくえ","tsukue","cái bàn học"]
  ]
};

const KATAKANA = {
  gojuon: [
    ["ア","a"],["イ","i"],["ウ","u"],["エ","e"],["オ","o"],
    ["カ","ka"],["キ","ki"],["ク","ku"],["ケ","ke"],["コ","ko"],
    ["サ","sa"],["シ",["shi","si"]],["ス","su"],["セ","se"],["ソ","so"],
    ["タ","ta"],["チ",["chi","ti"]],["ツ",["tsu","tu"]],["テ","te"],["ト","to"],
    ["ナ","na"],["ニ","ni"],["ヌ","nu"],["ネ","ne"],["ノ","no"],
    ["ハ","ha"],["ヒ","hi"],["フ",["fu","hu"]],["ヘ","he"],["ホ","ho"],
    ["マ","ma"],["ミ","mi"],["ム","mu"],["メ","me"],["モ","mo"],
    ["ヤ","ya"],["ユ","yu"],["ヨ","yo"],
    ["ラ","ra"],["リ","ri"],["ル","ru"],["レ","re"],["ロ","ro"],
    ["ワ","wa"],["ヲ",["wo","o"]],
    ["ン","n"]
  ],
  dakuten: [
    ["ガ","ga"],["ギ","gi"],["グ","gu"],["ゲ","ge"],["ゴ","go"],
    ["ザ","za"],["ジ",["ji","zi"]],["ズ","zu"],["ゼ","ze"],["ゾ","zo"],
    ["ダ","da"],["ヂ",["ji","di"]],["ヅ",["zu","du"]],["デ","de"],["ド","do"],
    ["バ","ba"],["ビ","bi"],["ブ","bu"],["ベ","be"],["ボ","bo"],
    ["パ","pa"],["ピ","pi"],["プ","pu"],["ペ","pe"],["ポ","po"]
  ],
  yoon: [
    ["キャ","kya"],["キュ","kyu"],["キョ","kyo"],
    ["シャ",["sha","sya"]],["シュ",["shu","syu"]],["ショ",["sho","syo"]],
    ["チャ",["cha","tya"]],["チュ",["chu","tyu"]],["チョ",["cho","tyo"]],
    ["ニャ","nya"],["ニュ","nyu"],["ニョ","nyo"],
    ["ヒャ","hya"],["ヒュ","hyu"],["ヒョ","hyo"],
    ["ミャ","mya"],["ミュ","myu"],["ミョ","myo"],
    ["リャ","rya"],["リュ","ryu"],["リョ","ryo"],
    ["ギャ","gya"],["ギュ","gyu"],["ギョ","gyo"],
    ["ジャ",["ja","zya"]],["ジュ",["ju","zyu"]],["ジョ",["jo","zyo"]],
    ["ビャ","bya"],["ビュ","byu"],["ビョ","byo"],
    ["ピャ","pya"],["ピュ","pyu"],["ピョ","pyo"]
  ],
  vidu: [
    ["アヒル","ahiru","con vịt"],["ライオン","raion","con sư tử"],["ゾウ","zou","con voi"],
    ["トラ","tora","con hổ"],["キリン","kirin","con hươu cao cổ"],["パンダ","panda","gấu trúc"],
    ["ラクダ","rakuda","con lạc đà"],["コアラ","koara","gấu koala"],["ペンギン","pengin","chim cánh cụt"],
    ["カメラ","kamera","máy ảnh"],["テレビ","terebi","ti vi"],["ラジオ","rajio","đài radio"],
    ["パソコン","pasokon","máy tính cá nhân"],["インターネット",["inta-netto","intaanetto"],"internet"],
    ["ニュース",["nyu-su","nyuusu"],"tin tức"],["スポーツ",["supo-tsu","supootsu"],"thể thao"],
    ["サッカー",["sakka-","sakkaa"],"bóng đá"],["テニス","tenisu","quần vợt"],
    ["ジョギング","jogingu","chạy bộ"],["コーヒー",["ko-hi-","koohii"],"cà phê"],
    ["ジュース",["ju-su","juusu"],"nước ép"],["パン","pan","bánh mì"],
    ["ケーキ",["ke-ki","keeki"],"bánh ngọt"],["チョコレート",["chokore-to","chokoreeto"],"sô-cô-la"],
    ["アイスクリーム",["aisukuri-mu","aisukuriimu"],"kem"],["レストラン","resutoran","nhà hàng"],
    ["ホテル","hoteru","khách sạn"],["タクシー",["takushi-","takushii"],"taxi"],
    ["バス","basu","xe buýt"],["タオル","taoru","khăn tắm"],
    ["シャンプー",["shanpu-","shanpuu"],"dầu gội"],["ソファー",["sofa-","sofaa"],"ghế sofa"],
    ["カレンダー",["karenda-","karendaa"],"lịch"],["ノート",["no-to","nooto"],"quyển vở"],
    ["ペン","pen","cây bút"],["ナイフ","naifu","con dao"],
    ["フォーク",["fo-ku","fooku"],"cái nĩa"],["スプーン",["supu-n","supuun"],"cái thìa"],
    ["ボタン","botan","cái nút"],["カード",["ka-do","kaado"],"thẻ"],
    ["チケット","chiketto","vé"],["パーティー",["pa-ti-","paatii"],"bữa tiệc"],
    ["ダンス","dansu","khiêu vũ"],["ピアノ","piano","đàn piano"],
    ["ギター",["gita-","gitaa"],"đàn guitar"],["メロン","meron","dưa lưới"],
    ["レモン","remon","quả chanh vàng"],["トマト","tomato","cà chua"],
    ["サラダ","sarada","salad"],["ワイン","wain","rượu vang"],
    ["キツネ","kitsune","con cáo"],["ウサギ","usagi","con thỏ"],["シマウマ","shimauma","ngựa vằn"],
    ["サイ","sai","con tê giác"],["ワニ","wani","con cá sấu"],["イルカ","iruka","con cá heo"],
    ["クジラ","kujira","con cá voi"],["ラッコ","rakko","rái cá biển"],["カバ","kaba","hà mã"],
    ["チーター",["chi-ta-","chiitaa"],"báo săn"],["ジャガー",["jaga-","jagaa"],"báo đốm"],
    ["ハムスター",["hamusuta-","hamusutaa"],"chuột hamster"],["モルモット","morumotto","chuột lang"],
    ["オウム","oumu","con vẹt"],["フクロウ","fukurou","cú mèo"],
    ["コンピューター",["konpyu-ta-","konpyuutaa"],"máy vi tính"],["スマートフォン",["suma-tofon","sumaatofon"],"điện thoại thông minh"],
    ["テーブル",["te-buru","teeburu"],"cái bàn"],["ベッド","beddo","giường ngủ"],["カーテン",["ka-ten","kaaten"],"rèm cửa"],
    ["ドア","doa","cửa ra vào"],["マンション","manshon","chung cư cao cấp"],["アパート",["apa-to","apaato"],"nhà chung cư"],
    ["エレベーター",["erebe-ta-","erebeetaa"],"thang máy"],["エスカレーター",["esukare-ta-","esukareetaa"],"thang cuốn"],
    ["デパート",["depa-to","depaato"],"trung tâm thương mại"],["スーパー",["su-pa-","suupaa"],"siêu thị"],
    ["コンビニ","konbini","cửa hàng tiện lợi"],["レジ","reji","quầy thu ngân"],["サイズ","saizu","kích cỡ"],
    ["カラー",["kara-","karaa"],"màu sắc"],["デザイン","dezain","thiết kế"],["アイデア","aidea","ý tưởng"],
    ["プレゼント","purezento","quà tặng"],["クリスマス","kurisumasu","Giáng sinh"],["ハロウィン","harowin","lễ hội Halloween"],
    ["イベント","ibento","sự kiện"],["チーム",["chi-mu","chiimu"],"đội nhóm"],
    ["リーダー",["ri-da-","riidaa"],"người lãnh đạo"],["ゲーム",["ge-mu","geemu"],"trò chơi"],
    ["アニメ","anime","phim hoạt hình"],["マンガ","manga","truyện tranh"],
    ["キャラクター",["kyarakuta-","kyarakutaa"],"nhân vật"],["ロボット","robotto","người máy"],
    ["ミルク","miruku","sữa"],["バター",["bata-","bataa"],"bơ"],["チーズ",["chi-zu","chiizu"],"phô mai"],
    ["ヨーグルト",["yo-guruto","yooguruto"],"sữa chua"],["ハンバーガー",["hanba-ga-","hanbaagaa"],"bánh hamburger"],
    ["ピザ","piza","pizza"]
  ]
};

/* ===== Kanji N5 (mode 4) ===== */
function stripDiacritics(s){
  return s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D');
}
function kanjiAns(...readings){
  const set = new Set();
  readings.forEach(r => { set.add(r); set.add(stripDiacritics(r)); });
  return Array.from(set);
}

const KANJI = {
  n5: [
    ["一", kanjiAns("nhất"), "Một\nOn: イチ、イツ ・ Kun: ひと（つ）"],
    ["二", kanjiAns("nhị"), "Hai, số hai\nOn: ニ、ジ ・ Kun: ふた（つ）"],
    ["三", kanjiAns("tam"), "Số ba\nOn: サン、ゾウ ・ Kun: みっ(つ)"],
    ["四", kanjiAns("tứ"), "Số bốn\nOn: シ ・ Kun: よっ(つ)"],
    ["五", kanjiAns("ngũ"), "Số năm\nOn: ゴ ・ Kun: いつつ、いつ"],
    ["六", kanjiAns("lục"), "Sáu, số sáu\nOn: ロク、リク ・ Kun: むっつ, むつ, むい"],
    ["七", kanjiAns("thất"), "Số bảy\nOn: シチ ・ Kun: なな(つ)"],
    ["八", kanjiAns("bát"), "Tám, số tám\nOn: ハチ ・ Kun: やっ(つ), よう, や(つ)"],
    ["九", kanjiAns("cửu"), "Chín (9)\nOn: キュウ、ク ・ Kun: ここの、ここの(つ)"],
    ["十", kanjiAns("thập"), "Mười\nOn: ジュウ、ジッ、ジュッ ・ Kun: とう、とお"],
    ["東", kanjiAns("đông"), "Phía đông\nOn: トウ ・ Kun: ひがし"],
    ["西", kanjiAns("tây"), "Phía tây\nOn: セイ、サイ、ス ・ Kun: にし"],
    ["南", kanjiAns("nam"), "Phía Nam\nOn: ナン、ナ ・ Kun: みなみ"],
    ["北", kanjiAns("bắc"), "Phía bắc\nOn: ホク ・ Kun: きた"],
    ["安", kanjiAns("an", "yên"), "Yên lành, an toàn, rẻ\nOn: アン ・ Kun: やす（い）"],
    ["飲", kanjiAns("ẩm"), "Uống, uống nước\nOn: イン、オン ・ Kun: の（む）"],
    ["雨", kanjiAns("vũ", "vú"), "Mưa\nOn: ウ ・ Kun: あめ、あま"],
    ["駅", kanjiAns("dịch"), "Ga (xe điện), trạm\nOn: エキ ・ Kun: –"],
    ["円", kanjiAns("viên"), "Vòng tròn, hình cầu, đồng yên\nOn: エン ・ Kun: まる(い)"],
    ["火", kanjiAns("hỏa"), "Lửa, cháy\nOn: カ ・ Kun: ひ、ほ"],
    ["下", kanjiAns("hạ"), "Phần dưới, phía dưới, hạ xuống, cho\nOn: カ、ゲ ・ Kun: した、もと、しも、さ（げる）、お（ろす）、くだ（る）、くだ（す）、お(りる)、さ(がる)、くだ(さる)"],
    ["何", kanjiAns("hà"), "Cái gì, thế nào, bao nhiêu\nOn: カ ・ Kun: なに、なん"],
    ["会", kanjiAns("hội"), "Gặp\nOn: カイ、エ ・ Kun: え、あう"],
    ["外", kanjiAns("ngoại"), "Bên ngoài, khác, rời ra\nOn: ガイ、ゲ ・ Kun: そと、ほか、はず(れる/す)"],
    ["学", kanjiAns("học"), "Học, khoa học, dạy dỗ\nOn: ガク ・ Kun: まな(ぶ)"],
    ["間", kanjiAns("gian"), "Ở giữa, khoảng thời gian\nOn: カン、ケン ・ Kun: あいだ, ま"],
    ["気", kanjiAns("khí"), "Hơi thở, khí\nOn: キ、ケ ・ Kun: いき"],
    ["休", kanjiAns("hưu"), "Nghỉ ngơi, cho nghỉ, được nghỉ\nOn: キュウ ・ Kun: やす(む), やす(める), やす(まる)"],
    ["魚", kanjiAns("ngư"), "Cá\nOn: ギョ ・ Kun: さかな"],
    ["金", kanjiAns("kim"), "Tiền, kim loại\nOn: キン、コン、ゴン ・ Kun: かね, かな"],
    ["空", kanjiAns("không", "khống"), "Bầu trời, bỏ trống\nOn: クウ ・ Kun: そら, あ(ける/く), から"],
    ["月", kanjiAns("nguyệt"), "Mặt trăng, tháng\nOn: ゲツ、ガツ ・ Kun: つき"],
    ["見", kanjiAns("kiến"), "Nhìn, ngắm, cho xem\nOn: ケン ・ Kun: み（る）, み（える）, み（せる）"],
    ["言", kanjiAns("ngôn"), "Từ ngữ, nói\nOn: ゲン、ゴン ・ Kun: こと, い(う)"],
    ["古", kanjiAns("cổ"), "Cũ, cổ\nOn: コ ・ Kun: ふる（い）"],
    ["後", kanjiAns("hậu"), "Sau, đằng sau, muộn\nOn: ゴ、コウ ・ Kun: のち, こう, うし(ろ), あと, おくれる"],
    ["午", kanjiAns("ngọ"), "Trưa\nOn: ゴ ・ Kun: –"],
    ["語", kanjiAns("ngữ"), "Nói chuyện, kể chuyện\nOn: ゴ ・ Kun: かた(る), かた(らう)"],
    ["校", kanjiAns("hiệu", "giáo"), "Trường học\nOn: コウ、キョウ ・ Kun: –"],
    ["口", kanjiAns("khẩu"), "Miệng\nOn: コウ、ク ・ Kun: くち"],
    ["行", kanjiAns("hành"), "Đi, tiến hành, dòng\nOn: コウ、ギョウ、アン ・ Kun: いく, ゆく, おこなう"],
    ["高", kanjiAns("cao"), "Cao, nâng cao, làm cao lên\nOn: コウ ・ Kun: たか(い), たかまる, たかめる"],
    ["国", kanjiAns("quốc"), "Đất nước\nOn: コク ・ Kun: くに"],
    ["今", kanjiAns("kim"), "Hiện tại, bây giờ\nOn: コン、キン ・ Kun: いま"],
    ["右", kanjiAns("hữu"), "Bên phải\nOn: ウ、ユウ ・ Kun: みぎ"],
    ["左", kanjiAns("tả"), "Bên trái, bất chính\nOn: サ、シャ ・ Kun: ひだり"],
    ["山", kanjiAns("sơn", "san"), "Núi non\nOn: サン、セン ・ Kun: やま"],
    ["子", kanjiAns("tử", "tý"), "Trẻ con\nOn: シ、ス、ツ ・ Kun: こ"],
    ["耳", kanjiAns("nhĩ"), "Tai\nOn: ジ ・ Kun: みみ"],
    ["時", kanjiAns("thời", "thì"), "Thời gian, giờ\nOn: ジ ・ Kun: とき"],
    ["車", kanjiAns("xa"), "Xe cộ, bánh xe\nOn: シャ ・ Kun: くるま"],
    ["社", kanjiAns("xã"), "Đền thờ, miếu\nOn: シャ ・ Kun: やしろ"],
    ["手", kanjiAns("thủ"), "Tay\nOn: シュ、ズ ・ Kun: て"],
    ["週", kanjiAns("chu"), "Tuần\nOn: シュウ ・ Kun: –"],
    ["出", kanjiAns("xuất"), "Xuất, rời đi, ra đi\nOn: シュツ、スイ ・ Kun: だ(す), で(る)"],
    ["書", kanjiAns("thư"), "Viết\nOn: ショ ・ Kun: か(く)"],
    ["小", kanjiAns("tiểu"), "Nhỏ bé, hẹp\nOn: ショウ ・ Kun: ちい(さい), こ, お"],
    ["少", kanjiAns("thiếu", "thiểu"), "Một chút, một ít\nOn: ショウ ・ Kun: すこ(し), すく(ない)"],
    ["上", kanjiAns("thượng"), "Phía trên, trên (thượng)\nOn: ジョウ、ショウ、シャン ・ Kun: うえ、かみ、あ（げる）、あ（がる）"],
    ["食", kanjiAns("thực"), "Ăn\nOn: ショク、ジキ ・ Kun: たべる, くう, くらう"],
    ["新", kanjiAns("tân"), "Mới\nOn: シン ・ Kun: あたら(しい), あら(た)"],
    ["人", kanjiAns("nhân"), "Người\nOn: ジン、ニン ・ Kun: ひと"],
    ["水", kanjiAns("thủy"), "Nước, chất lỏng\nOn: スイ ・ Kun: みず"],
    ["生", kanjiAns("sinh"), "Sinh sống, làm sống lại, đẻ, sản xuất, lớn lên, sống\nOn: セイ、ショウ ・ Kun: い(きる/ける), いかす, う(まれる/む), は(やす/える), なま"],
    ["川", kanjiAns("xuyên"), "Con sông\nOn: セン ・ Kun: かわ"],
    ["千", kanjiAns("thiên"), "Ngàn (1000)\nOn: セン ・ Kun: ち"],
    ["先", kanjiAns("tiên"), "Trước, đầu chỗ, tổ tiên\nOn: セン ・ Kun: さき"],
    ["前", kanjiAns("tiền"), "Trước, phía trước, sớm, tiến, đi tới\nOn: ゼン ・ Kun: まえ"],
    ["足", kanjiAns("túc"), "Chân, bước, đầy đủ, thêm vào\nOn: ソク ・ Kun: あし, た(る/す), た(りる)"],
    ["多", kanjiAns("đa"), "Nhiều, đầy\nOn: タ ・ Kun: おお(い)"],
    ["大", kanjiAns("đại"), "To lớn, nhiều\nOn: ダイ、タイ ・ Kun: おお(きい）、おお（い）"],
    ["男", kanjiAns("nam"), "Đàn ông\nOn: ダン、ナン ・ Kun: おとこ"],
    ["女", kanjiAns("nữ"), "Phụ nữ, giống cái\nOn: ジョ、ニョ、ニョウ ・ Kun: おんな, め"],
    ["中", kanjiAns("trung"), "Ở giữa, bên trong, suốt\nOn: チュウ ・ Kun: なか"],
    ["長", kanjiAns("trường"), "Dài\nOn: チョウ ・ Kun: なが(い)"],
    ["天", kanjiAns("thiên"), "Trời, tự nhiên, thời tiết\nOn: テン ・ Kun: あめ、あま"],
    ["店", kanjiAns("điếm"), "Cửa hàng\nOn: テン ・ Kun: みせ"],
    ["電", kanjiAns("điện"), "Điện\nOn: デン ・ Kun: –"],
    ["土", kanjiAns("thổ"), "Đất, thổ\nOn: ド、ト ・ Kun: つち"],
    ["道", kanjiAns("đạo"), "Con đường, đạo lý\nOn: ドウ、トウ ・ Kun: みち"],
    ["読", kanjiAns("độc"), "Đọc, nói\nOn: ドク、トク、トウ ・ Kun: よ(む)"],
    ["日", kanjiAns("nhật"), "Ngày, mặt trời, nước Nhật, ban ngày\nOn: ニチ、ジツ ・ Kun: ひ, -か"],
    ["入", kanjiAns("nhập"), "Đi vào, cho vào, nhét vào\nOn: ニュウ、ニッ ・ Kun: はい(る), い(る/れる)"],
    ["年", kanjiAns("niên"), "Năm, tuổi\nOn: ネン ・ Kun: とし"],
    ["買", kanjiAns("mãi"), "Mua\nOn: バイ ・ Kun: か(う)"],
    ["白", kanjiAns("bạch"), "Màu trắng\nOn: ハク、ビャク ・ Kun: しろ(い), しろ, し"],
    ["半", kanjiAns("bán"), "Một nửa, giữa\nOn: ハン ・ Kun: なか（ば）"],
    ["百", kanjiAns("bách"), "Một trăm\nOn: ヒャク、ビャク ・ Kun: –"],
    ["父", kanjiAns("phụ"), "Cha, bố\nOn: フ ・ Kun: ちち"],
    ["分", kanjiAns("phân"), "Phút, phân chia, hiểu\nOn: ブン、フン、ブ ・ Kun: わ(ける/かつ), わ(かれる), わ(かる)"],
    ["聞", kanjiAns("văn"), "Nghe, hỏi\nOn: ブン、モン ・ Kun: き(く), き(こえる)"],
    ["母", kanjiAns("mẫu"), "Mẹ, nguồn gốc\nOn: ボ ・ Kun: はは"],
    ["木", kanjiAns("mộc"), "Cây, gỗ\nOn: ボク、モク ・ Kun: き、こ"],
    ["本", kanjiAns("bản", "bổn"), "Sách, gốc, chính, đếm vật\nOn: ホン ・ Kun: もと"],
    ["毎", kanjiAns("mỗi"), "Mỗi, mọi\nOn: マイ ・ Kun: –"],
    ["万", kanjiAns("vạn"), "10 ngàn\nOn: マン、バン ・ Kun: –"],
    ["名", kanjiAns("danh"), "Tên, tiếng tăm, danh dự\nOn: メイ、ミョウ ・ Kun: な"],
    ["目", kanjiAns("mục"), "Mắt, tầm mắt\nOn: モク、ボク ・ Kun: め、ま"],
    ["友", kanjiAns("hữu"), "Bạn\nOn: ユウ ・ Kun: とも"],
    ["来", kanjiAns("lai"), "Gây nên, đến, tới\nOn: ライ、タイ ・ Kun: きた(す/る), く(る)"],
    ["立", kanjiAns("lập"), "Đứng dậy, dựng lên\nOn: リツ、リュウ ・ Kun: た(つ), た(てる)"],
    ["話", kanjiAns("thoại"), "Nói chuyện, câu chuyện\nOn: ワ ・ Kun: はなし, はな(す)"],
  ]
};","benkyoushite"],
["かいます","","かって","katte"],
["のみます","","のんで","nonde"],
["すいます","","すって","sutte"],
["みます","","みて","mite"],
["ききます","","きいて","kiite"],
["散歩します","","さんぽして","sanposhite"],
["かきます","","かいて","kaite"],
["とります","","とって","totte"],
["あいます","","あって","atte"],
["します","","して","shite"],
["きります","","きって","kitte"],
["おくります","","おくって","okutte"],
["あげます","","あげて","agete"],
["もらいます","","もらって","moratte"],
["かします","","かして","kashite"],
["きます","đến","きて","kite"],
["食事します","","しょくじして","shokujishite"],
["おしえます","","おしえて","oshiete"],
["ならいます","","ならって","naratte"],
["かけます","","かけて","kakete"],
["かえります","","かえって","kaette"],
["わかります","","わかって","wakatte"],
["あります","","あって","atte"],
["います","","いて","ite"],
["出張します","","しゅっちょうして","shutchoushite"],
["あそびます","","あそんで","asonde"],
["うります","","うって","utte"],
["しります","","しって","shitte"],
["すみます","","すんで","sunde"],
["研究します","","けんきゅうして","kenkyuushite"],
["のります","","のって","notte"],
["おります","","おりて","orite"],
["のりかえます","","のりかえて","norikaete"],
["あびます","","あびて","abite"],
["残業します","","ざんぎょうして","zangyoushite"],
["わすれます","","わすれて","wasurete"],
["なくします","","なくして","nakushite"],
["はらいます","","はらって","haratte"],
["かえします","","かえして","kaeshite"],
["予約します","","よやくして","yoyakushite"],
["あらいます","","あらって","aratte"],
["ひきます","","ひいて","hiite"],
["うたいます","","うたって","utatte"],
["あつめます","","あつめて","atsumete"],
["すてます","","すてて","sutete"],
["かえます","","かえて","kaete"],
["いそぎます","","いそいで","isoide"],
["しらべます","","しらべて","shirabete"],
["修理します","","しゅうりして","shuurishite"],
["おもいます","","おもって","omotte"],
["いいます","","いって","itte"],
["かちます","","かって","katte"],
["まけます","","まけて","makete"],
["役に立ちます","","やくにたって","yakunitatte"],
["うごきます","","うごいて","ugoite"],
["やめます","","やめて","yamete"],
["きをつけます","","きをつけて","kiwotsukete"],
["留学します","","りゅうがくして","ryuugakushite"],
["はきます","","はいて","haite"],
["かぶります","","かぶって","kabutte"],
["うまれます","","うまれて","umarete"],
["まわします","","まわして","mawashite"],
["およぎます","","およいで","oyoide"],
["むかえます","","むかえて","mukaete"],
["きます","mặc","きて","kite"],
["つかれます","","つかれて","tsukarete"],
["結婚します","","けっこんして","kekkonshite"],
["買い物します","","かいものして","kaimonoshite"],
["たべます","","たべて","tabete"],
["かります","","かりて","karite"],
["はなします","","はなして","hanashite"],
["はいります","","はいって","haitte"],
["つけます","","つけて","tsukete"],
["あけます","","あけて","akete"],
["けします","","けして","keshite"],
["しめます","","しめて","shimete"],
["のぼります","","のぼって","nobotte"],
["まちます","","まって","matte"],
["てつだいます","","てつだって","tetsudatte"],
["つかいます","","つかって","tsukatte"],
["みせます","","みせて","misete"],
["すわります","","すわって","suwatte"],
["ねます","","ねて","nete"],
["たちます","","たって","tatte"],
["でます","","でて","dete"],
["ふります","","ふって","futte"],
["コピーします","","コピーして","kopishite"],
["つくります","","つくって","tsukutte"],
["おわります","","おわって","owatte"],
["とまります","","とまって","tomatte"],
["いれます","","いれて","irete"],
["だします","","だして","dashite"],
["おろします","","おろして","oroshite"],
["おします","","おして","oshite"],
["はじめます","","はじめて","hajimete"],
["見学します","","けんがくして","kengakushite"],
["電話します","","でんわして","denwashite"],
["でかけます","","でかけて","dekakete"],
["ぬぎます","","ぬいで","nuide"],
["もっていきます","","もっていって","motteitte"],
["心配します","","しんぱいして","shinpaishite"],
["おぼえます","","おぼえて","oboete"],
["かかります","","かかって","kakatte"],
["おきます","đặt, để","おいて","oite"],
["洗濯します","","せんたくして","sentakushite"],
["なります","","なって","natte"],
["練習します","","れんしゅうして","renshuushite"],
["運転します","","うんてんして","untenshite"],
["できます","","できて","dekite"],
["いります","","いって","itte"],
["掃除します","","そうじして","soujishite"],
["さわります","","さわって","sawatte"],
["あるきます","","あるいて","aruite"],
["わたします","","わたして","watashite"],
["くれます","","くれて","kurete"],
["なおします","","なおして","naoshite"],
["つれてきます","","つれてきて","tsuretekite"],
["案内します","","あんないして","annaishite"],
["かんがえます","","かんがえて","kangaete"],
["つきます","","ついて","tsuite"],
["たります","","たりて","tarite"],
["説明します","","せつめいして","setsumeishite"],
["がんばります","","がんばって","ganbatte"],
["かえます","","かえて","kaete"],
["まがります","","まがって","magatte"],
["つれていきます","","つれていって","tsureteitte"]
];

const HIRAGANA = {
  gojuon: [
    ["あ","a"],["い","i"],["う","u"],["え","e"],["お","o"],
    ["か","ka"],["き","ki"],["く","ku"],["け","ke"],["こ","ko"],
    ["さ","sa"],["し",["shi","si"]],["す","su"],["せ","se"],["そ","so"],
    ["た","ta"],["ち",["chi","ti"]],["つ",["tsu","tu"]],["て","te"],["と","to"],
    ["な","na"],["に","ni"],["ぬ","nu"],["ね","ne"],["の","no"],
    ["は","ha"],["ひ","hi"],["ふ",["fu","hu"]],["へ","he"],["ほ","ho"],
    ["ま","ma"],["み","mi"],["む","mu"],["め","me"],["も","mo"],
    ["や","ya"],["ゆ","yu"],["よ","yo"],
    ["ら","ra"],["り","ri"],["る","ru"],["れ","re"],["ろ","ro"],
    ["わ","wa"],["を",["wo","o"]],
    ["ん","n"]
  ],
  dakuten: [
    ["が","ga"],["ぎ","gi"],["ぐ","gu"],["げ","ge"],["ご","go"],
    ["ざ","za"],["じ",["ji","zi"]],["ず","zu"],["ぜ","ze"],["ぞ","zo"],
    ["だ","da"],["ぢ",["ji","di"]],["づ",["zu","du"]],["で","de"],["ど","do"],
    ["ば","ba"],["び","bi"],["ぶ","bu"],["べ","be"],["ぼ","bo"],
    ["ぱ","pa"],["ぴ","pi"],["ぷ","pu"],["ぺ","pe"],["ぽ","po"]
  ],
  yoon: [
    ["きゃ","kya"],["きゅ","kyu"],["きょ","kyo"],
    ["しゃ",["sha","sya"]],["しゅ",["shu","syu"]],["しょ",["sho","syo"]],
    ["ちゃ",["cha","tya"]],["ちゅ",["chu","tyu"]],["ちょ",["cho","tyo"]],
    ["にゃ","nya"],["にゅ","nyu"],["にょ","nyo"],
    ["ひゃ","hya"],["ひゅ","hyu"],["ひょ","hyo"],
    ["みゃ","mya"],["みゅ","myu"],["みょ","myo"],
    ["りゃ","rya"],["りゅ","ryu"],["りょ","ryo"],
    ["ぎゃ","gya"],["ぎゅ","gyu"],["ぎょ","gyo"],
    ["じゃ",["ja","zya"]],["じゅ",["ju","zyu"]],["じょ",["jo","zyo"]],
    ["びゃ","bya"],["びゅ","byu"],["びょ","byo"],
    ["ぴゃ","pya"],["ぴゅ","pyu"],["ぴょ","pyo"]
  ],
  vidu: [
    ["あい","ai","tình yêu"],["あさ","asa","buổi sáng"],["あめ","ame","mưa"],
    ["いえ","ie","nhà"],["いす","isu","cái ghế"],["いぬ","inu","con chó"],
    ["うた","uta","bài hát"],["うみ","umi","biển"],["えき","eki","nhà ga"],
    ["おかね","okane","tiền"],["おちゃ","ocha","trà"],["おとこ","otoko","đàn ông"],
    ["おんな","onna","phụ nữ"],["かお","kao","khuôn mặt"],["かさ","kasa","cái ô"],
    ["かぜ","kaze","gió (cảm cúm)"],["かみ","kami","tóc (giấy)"],["き","ki","cây"],
    ["くつ","kutsu","giày"],["くも","kumo","mây"],["くるま","kuruma","xe hơi"],
    ["こえ","koe","giọng nói"],["ことば","kotoba","từ ngữ"],["さかな","sakana","con cá"],
    ["さくら","sakura","hoa anh đào"],["しお","shio","muối"],["しま","shima","hòn đảo"],
    ["すし","sushi","sushi"],["たまご","tamago","quả trứng"],["ちから","chikara","sức mạnh"],
    ["つき","tsuki","mặt trăng"],["とけい","tokei","đồng hồ"],["とり","tori","con chim"],
    ["なつ","natsu","mùa hè"],["にく","niku","thịt"],["ねこ","neko","con mèo"],
    ["はな","hana","hoa"],["はる","haru","mùa xuân"],["ひと","hito","con người"],
    ["ふゆ","fuyu","mùa đông"],["ほし","hoshi","ngôi sao"],["まち","machi","thị trấn"],
    ["みず","mizu","nước"],["みみ","mimi","lỗ tai"],["むし","mushi","côn trùng"],
    ["め","me","con mắt"],["やま","yama","núi"],["ゆき","yuki","tuyết"],
    ["よる","yoru","ban đêm"],["わたし","watashi","tôi"],
    ["あたま","atama","đầu"],["あに","ani","anh trai"],["あね","ane","chị gái"],
    ["いもうと","imouto","em gái"],["おとうと","otouto","em trai"],["ちち","chichi","bố"],
    ["はは","haha","mẹ"],["そふ","sofu","ông"],["そぼ","sobo","bà"],
    ["かぞく","kazoku","gia đình"],["ともだち","tomodachi","bạn bè"],["せんせい","sensei","giáo viên"],
    ["がくせい","gakusei","học sinh"],["かいしゃ","kaisha","công ty"],["しごと","shigoto","công việc"],
    ["でんわ","denwa","điện thoại"],["てがみ","tegami","lá thư"],["きっぷ","kippu","vé xe/tàu"],
    ["えいが","eiga","phim điện ảnh"],["おんがく","ongaku","âm nhạc"],["しゃしん","shashin","ảnh chụp"],
    ["にわ","niwa","sân vườn"],["へや","heya","căn phòng"],["まど","mado","cửa sổ"],
    ["とびら","tobira","cánh cửa"],["かぎ","kagi","chìa khóa"],["はし","hashi","đôi đũa"],
    ["さら","sara","cái đĩa"],["ちゃわん","chawan","cái bát cơm"],["たべもの","tabemono","đồ ăn"],
    ["のみもの","nomimono","đồ uống"],["やさい","yasai","rau củ"],["くだもの","kudamono","trái cây"],
    ["にわとり","niwatori","con gà"],["うし","ushi","con bò"],["うま","uma","con ngựa"],
    ["ぶた","buta","con lợn"],["ひつじ","hitsuji","con cừu"],["さる","saru","con khỉ"],
    ["かえる","kaeru","con ếch"],["ちょう","chou","con bướm"],["はち","hachi","con ong"],
    ["くさ","kusa","cỏ"],["こおり","koori","nước đá"],["ゆびわ","yubiwa","nhẫn đeo tay"],
    ["ぼうし","boushi","mũ nón"],["くつした","kutsushita","vớ/tất"],["めがね","megane","kính mắt"],
    ["かばん","kaban","cái cặp"],["つくえ","tsukue","cái bàn học"]
  ]
};

const KATAKANA = {
  gojuon: [
    ["ア","a"],["イ","i"],["ウ","u"],["エ","e"],["オ","o"],
    ["カ","ka"],["キ","ki"],["ク","ku"],["ケ","ke"],["コ","ko"],
    ["サ","sa"],["シ",["shi","si"]],["ス","su"],["セ","se"],["ソ","so"],
    ["タ","ta"],["チ",["chi","ti"]],["ツ",["tsu","tu"]],["テ","te"],["ト","to"],
    ["ナ","na"],["ニ","ni"],["ヌ","nu"],["ネ","ne"],["ノ","no"],
    ["ハ","ha"],["ヒ","hi"],["フ",["fu","hu"]],["ヘ","he"],["ホ","ho"],
    ["マ","ma"],["ミ","mi"],["ム","mu"],["メ","me"],["モ","mo"],
    ["ヤ","ya"],["ユ","yu"],["ヨ","yo"],
    ["ラ","ra"],["リ","ri"],["ル","ru"],["レ","re"],["ロ","ro"],
    ["ワ","wa"],["ヲ",["wo","o"]],
    ["ン","n"]
  ],
  dakuten: [
    ["ガ","ga"],["ギ","gi"],["グ","gu"],["ゲ","ge"],["ゴ","go"],
    ["ザ","za"],["ジ",["ji","zi"]],["ズ","zu"],["ゼ","ze"],["ゾ","zo"],
    ["ダ","da"],["ヂ",["ji","di"]],["ヅ",["zu","du"]],["デ","de"],["ド","do"],
    ["バ","ba"],["ビ","bi"],["ブ","bu"],["ベ","be"],["ボ","bo"],
    ["パ","pa"],["ピ","pi"],["プ","pu"],["ペ","pe"],["ポ","po"]
  ],
  yoon: [
    ["キャ","kya"],["キュ","kyu"],["キョ","kyo"],
    ["シャ",["sha","sya"]],["シュ",["shu","syu"]],["ショ",["sho","syo"]],
    ["チャ",["cha","tya"]],["チュ",["chu","tyu"]],["チョ",["cho","tyo"]],
    ["ニャ","nya"],["ニュ","nyu"],["ニョ","nyo"],
    ["ヒャ","hya"],["ヒュ","hyu"],["ヒョ","hyo"],
    ["ミャ","mya"],["ミュ","myu"],["ミョ","myo"],
    ["リャ","rya"],["リュ","ryu"],["リョ","ryo"],
    ["ギャ","gya"],["ギュ","gyu"],["ギョ","gyo"],
    ["ジャ",["ja","zya"]],["ジュ",["ju","zyu"]],["ジョ",["jo","zyo"]],
    ["ビャ","bya"],["ビュ","byu"],["ビョ","byo"],
    ["ピャ","pya"],["ピュ","pyu"],["ピョ","pyo"]
  ],
  vidu: [
    ["アヒル","ahiru","con vịt"],["ライオン","raion","con sư tử"],["ゾウ","zou","con voi"],
    ["トラ","tora","con hổ"],["キリン","kirin","con hươu cao cổ"],["パンダ","panda","gấu trúc"],
    ["ラクダ","rakuda","con lạc đà"],["コアラ","koara","gấu koala"],["ペンギン","pengin","chim cánh cụt"],
    ["カメラ","kamera","máy ảnh"],["テレビ","terebi","ti vi"],["ラジオ","rajio","đài radio"],
    ["パソコン","pasokon","máy tính cá nhân"],["インターネット",["inta-netto","intaanetto"],"internet"],
    ["ニュース",["nyu-su","nyuusu"],"tin tức"],["スポーツ",["supo-tsu","supootsu"],"thể thao"],
    ["サッカー",["sakka-","sakkaa"],"bóng đá"],["テニス","tenisu","quần vợt"],
    ["ジョギング","jogingu","chạy bộ"],["コーヒー",["ko-hi-","koohii"],"cà phê"],
    ["ジュース",["ju-su","juusu"],"nước ép"],["パン","pan","bánh mì"],
    ["ケーキ",["ke-ki","keeki"],"bánh ngọt"],["チョコレート",["chokore-to","chokoreeto"],"sô-cô-la"],
    ["アイスクリーム",["aisukuri-mu","aisukuriimu"],"kem"],["レストラン","resutoran","nhà hàng"],
    ["ホテル","hoteru","khách sạn"],["タクシー",["takushi-","takushii"],"taxi"],
    ["バス","basu","xe buýt"],["タオル","taoru","khăn tắm"],
    ["シャンプー",["shanpu-","shanpuu"],"dầu gội"],["ソファー",["sofa-","sofaa"],"ghế sofa"],
    ["カレンダー",["karenda-","karendaa"],"lịch"],["ノート",["no-to","nooto"],"quyển vở"],
    ["ペン","pen","cây bút"],["ナイフ","naifu","con dao"],
    ["フォーク",["fo-ku","fooku"],"cái nĩa"],["スプーン",["supu-n","supuun"],"cái thìa"],
    ["ボタン","botan","cái nút"],["カード",["ka-do","kaado"],"thẻ"],
    ["チケット","chiketto","vé"],["パーティー",["pa-ti-","paatii"],"bữa tiệc"],
    ["ダンス","dansu","khiêu vũ"],["ピアノ","piano","đàn piano"],
    ["ギター",["gita-","gitaa"],"đàn guitar"],["メロン","meron","dưa lưới"],
    ["レモン","remon","quả chanh vàng"],["トマト","tomato","cà chua"],
    ["サラダ","sarada","salad"],["ワイン","wain","rượu vang"],
    ["キツネ","kitsune","con cáo"],["ウサギ","usagi","con thỏ"],["シマウマ","shimauma","ngựa vằn"],
    ["サイ","sai","con tê giác"],["ワニ","wani","con cá sấu"],["イルカ","iruka","con cá heo"],
    ["クジラ","kujira","con cá voi"],["ラッコ","rakko","rái cá biển"],["カバ","kaba","hà mã"],
    ["チーター",["chi-ta-","chiitaa"],"báo săn"],["ジャガー",["jaga-","jagaa"],"báo đốm"],
    ["ハムスター",["hamusuta-","hamusutaa"],"chuột hamster"],["モルモット","morumotto","chuột lang"],
    ["オウム","oumu","con vẹt"],["フクロウ","fukurou","cú mèo"],
    ["コンピューター",["konpyu-ta-","konpyuutaa"],"máy vi tính"],["スマートフォン",["suma-tofon","sumaatofon"],"điện thoại thông minh"],
    ["テーブル",["te-buru","teeburu"],"cái bàn"],["ベッド","beddo","giường ngủ"],["カーテン",["ka-ten","kaaten"],"rèm cửa"],
    ["ドア","doa","cửa ra vào"],["マンション","manshon","chung cư cao cấp"],["アパート",["apa-to","apaato"],"nhà chung cư"],
    ["エレベーター",["erebe-ta-","erebeetaa"],"thang máy"],["エスカレーター",["esukare-ta-","esukareetaa"],"thang cuốn"],
    ["デパート",["depa-to","depaato"],"trung tâm thương mại"],["スーパー",["su-pa-","suupaa"],"siêu thị"],
    ["コンビニ","konbini","cửa hàng tiện lợi"],["レジ","reji","quầy thu ngân"],["サイズ","saizu","kích cỡ"],
    ["カラー",["kara-","karaa"],"màu sắc"],["デザイン","dezain","thiết kế"],["アイデア","aidea","ý tưởng"],
    ["プレゼント","purezento","quà tặng"],["クリスマス","kurisumasu","Giáng sinh"],["ハロウィン","harowin","lễ hội Halloween"],
    ["イベント","ibento","sự kiện"],["チーム",["chi-mu","chiimu"],"đội nhóm"],
    ["リーダー",["ri-da-","riidaa"],"người lãnh đạo"],["ゲーム",["ge-mu","geemu"],"trò chơi"],
    ["アニメ","anime","phim hoạt hình"],["マンガ","manga","truyện tranh"],
    ["キャラクター",["kyarakuta-","kyarakutaa"],"nhân vật"],["ロボット","robotto","người máy"],
    ["ミルク","miruku","sữa"],["バター",["bata-","bataa"],"bơ"],["チーズ",["chi-zu","chiizu"],"phô mai"],
    ["ヨーグルト",["yo-guruto","yooguruto"],"sữa chua"],["ハンバーガー",["hanba-ga-","hanbaagaa"],"bánh hamburger"],
    ["ピザ","piza","pizza"]
  ]
};
