const て = [
["おきます","thức dậy","おきて","okite"],
["やすみます","","やすんで","yasunde"],
["はたらきます","","はたらいて","hataraite"],
["勉強します","","べんきょうして","benkyoushite"],
["かいます","","かって","katte"],
["のみます","","のんで","nonde"],
["すいます","","すって","sutte"],
["みます","","みて","mite"],
["ききます","","きいて","kiite"],
["散歩します","","さんぽして","sanposhite"],
["かきます","","かいて","kaite"],
["とります","","とって","totte"],
["あいます","","あって","atte"],
["します","","して","shite"],
["きります","","きって","kitte"],
["おくります","","おくって","okutte"],
["あげます","","あげて","agete"],
["もらいます","","もらって","moratte"],
["かします","","かして","kashite"],
["きます","đến","きて","kite"],
["食事します","","しょくじして","shokujishite"],
["おしえます","","おしえて","oshiete"],
["ならいます","","ならって","naratte"],
["かけます","","かけて","kakete"],
["かえります","","かえって","kaette"],
["わかります","","わかって","wakatte"],
["あります","","あって","atte"],
["います","","いて","ite"],
["出張します","","しゅっちょうして","shutchoushite"],
["あそびます","","あそんで","asonde"],
["うります","","うって","utte"],
["しります","","しって","shitte"],
["すみます","","すんで","sunde"],
["研究します","","けんきゅうして","kenkyuushite"],
["のります","","のって","notte"],
["おります","","おりて","orite"],
["のりかえます","","のりかえて","norikaete"],
["あびます","","あびて","abite"],
["残業します","","ざんぎょうして","zangyoushite"],
["わすれます","","わすれて","wasurete"],
["なくします","","なくして","nakushite"],
["はらいます","","はらって","haratte"],
["かえします","","かえして","kaeshite"],
["予約します","","よやくして","yoyakushite"],
["あらいます","","あらって","aratte"],
["ひきます","","ひいて","hiite"],
["うたいます","","うたって","utatte"],
["あつめます","","あつめて","atsumete"],
["すてます","","すてて","sutete"],
["かえます","","かえて","kaete"],
["いそぎます","","いそいで","isoide"],
["しらべます","","しらべて","shirabete"],
["修理します","","しゅうりして","shuurishite"],
["おもいます","","おもって","omotte"],
["いいます","","いって","itte"],
["かちます","","かって","katte"],
["まけます","","まけて","makete"],
["役に立ちます","","やくにたって","yakunitatte"],
["うごきます","","うごいて","ugoite"],
["やめます","","やめて","yamete"],
["きをつけます","","きをつけて","kiwotsukete"],
["留学します","","りゅうがくして","ryuugakushite"],
["はきます","","はいて","haite"],
["かぶります","","かぶって","kabutte"],
["うまれます","","うまれて","umarete"],
["まわします","","まわして","mawashite"],
["およぎます","","およいで","oyoide"],
["むかえます","","むかえて","mukaete"],
["きます","mặc","きて","kite"],
["つかれます","","つかれて","tsukarete"],
["結婚します","","けっこんして","kekkonshite"],
["買い物します","","かいものして","kaimonoshite"],
["たべます","","たべて","tabete"],
["かります","","かりて","karite"],
["はなします","","はなして","hanashite"],
["はいります","","はいって","haitte"],
["つけます","","つけて","tsukete"],
["あけます","","あけて","akete"],
["けします","","けして","keshite"],
["しめます","","しめて","shimete"],
["のぼります","","のぼって","nobotte"],
["まちます","","まって","matte"],
["てつだいます","","てつだって","tetsudatte"],
["つかいます","","つかって","tsukatte"],
["みせます","","みせて","misete"],
["すわります","","すわって","suwatte"],
["ねます","","ねて","nete"],
["たちます","","たって","tatte"],
["でます","","でて","dete"],
["ふります","","ふって","futte"],
["コピーします","","コピーして","kopishite"],
["つくります","","つくって","tsukutte"],
["おわります","","おわって","owatte"],
["とまります","","とまって","tomatte"],
["いれます","","いれて","irete"],
["だします","","だして","dashite"],
["おろします","","おろして","oroshite"],
["おします","","おして","oshite"],
["はじめます","","はじめて","hajimete"],
["見学します","","けんがくして","kengakushite"],
["電話します","","でんわして","denwashite"],
["でかけます","","でかけて","dekakete"],
["ぬぎます","","ぬいで","nuide"],
["もっていきます","","もっていって","motteitte"],
["心配します","","しんぱいして","shinpaishite"],
["おぼえます","","おぼえて","oboete"],
["かかります","","かかって","kakatte"],
["おきます","đặt, để","おいて","oite"],
["洗濯します","","せんたくして","sentakushite"],
["なります","","なって","natte"],
["練習します","","れんしゅうして","renshuushite"],
["運転します","","うんてんして","untenshite"],
["できます","","できて","dekite"],
["いります","","いって","itte"],
["掃除します","","そうじして","soujishite"],
["さわります","","さわって","sawatte"],
["あるきます","","あるいて","aruite"],
["わたします","","わたして","watashite"],
["くれます","","くれて","kurete"],
["なおします","","なおして","naoshite"],
["つれてきます","","つれてきて","tsuretekite"],
["案内します","","あんないして","annaishite"],
["かんがえます","","かんがえて","kangaete"],
["つきます","","ついて","tsuite"],
["たります","","たりて","tarite"],
["説明します","","せつめいして","setsumeishite"],
["がんばります","","がんばって","ganbatte"],
["かえます","","かえて","kaete"],
["まがります","","まがって","magatte"],
["つれていきます","","つれていって","tsureteitte"]
];

const HIRAGANA = {
  gojuon: [
    ["あ","a"],["い","i"],["う","u"],["え","e"],["お","o"],
    ["か","ka"],["き","ki"],["く","ku"],["け","ke"],["こ","ko"],
    ["さ","sa"],["し",["shi","si"]],["す","su"],["せ","se"],["そ","so"],
    ["た","ta"],["ち",["chi","ti"]],["つ",["tsu","tu"]],["て","te"],["と","to"],
    ["な","na"],["に","ni"],["ぬ","nu"],["ね","ne"],["の","no"],
    ["は","ha"],["ひ","hi"],["ふ",["fu","hu"]],["へ","he"],["ほ","ho"],
    ["ま","ma"],["み","mi"],["む","mu"],["め","me"],["も","mo"],
    ["や","ya"],["ゆ","yu"],["よ","yo"],
    ["ら","ra"],["り","ri"],["る","ru"],["れ","re"],["ろ","ro"],
    ["わ","wa"],["を",["wo","o"]],
    ["ん","n"]
  ],
  dakuten: [
    ["が","ga"],["ぎ","gi"],["ぐ","gu"],["げ","ge"],["ご","go"],
    ["ざ","za"],["じ",["ji","zi"]],["ず","zu"],["ぜ","ze"],["ぞ","zo"],
    ["だ","da"],["ぢ",["ji","di"]],["づ",["zu","du"]],["で","de"],["ど","do"],
    ["ば","ba"],["び","bi"],["ぶ","bu"],["べ","be"],["ぼ","bo"],
    ["ぱ","pa"],["ぴ","pi"],["ぷ","pu"],["ぺ","pe"],["ぽ","po"]
  ],
  yoon: [
    ["きゃ","kya"],["きゅ","kyu"],["きょ","kyo"],
    ["しゃ",["sha","sya"]],["しゅ",["shu","syu"]],["しょ",["sho","syo"]],
    ["ちゃ",["cha","tya"]],["ちゅ",["chu","tyu"]],["ちょ",["cho","tyo"]],
    ["にゃ","nya"],["にゅ","nyu"],["にょ","nyo"],
    ["ひゃ","hya"],["ひゅ","hyu"],["ひょ","hyo"],
    ["みゃ","mya"],["みゅ","myu"],["みょ","myo"],
    ["りゃ","rya"],["りゅ","ryu"],["りょ","ryo"],
    ["ぎゃ","gya"],["ぎゅ","gyu"],["ぎょ","gyo"],
    ["じゃ",["ja","zya"]],["じゅ",["ju","zyu"]],["じょ",["jo","zyo"]],
    ["びゃ","bya"],["びゅ","byu"],["びょ","byo"],
    ["ぴゃ","pya"],["ぴゅ","pyu"],["ぴょ","pyo"]
  ],
  vidu: [
    ["あい","ai","tình yêu"],["あさ","asa","buổi sáng"],["あめ","ame","mưa"],
    ["いえ","ie","nhà"],["いす","isu","cái ghế"],["いぬ","inu","con chó"],
    ["うた","uta","bài hát"],["うみ","umi","biển"],["えき","eki","nhà ga"],
    ["おかね","okane","tiền"],["おちゃ","ocha","trà"],["おとこ","otoko","đàn ông"],
    ["おんな","onna","phụ nữ"],["かお","kao","khuôn mặt"],["かさ","kasa","cái ô"],
    ["かぜ","kaze","gió (cảm cúm)"],["かみ","kami","tóc (giấy)"],["き","ki","cây"],
    ["くつ","kutsu","giày"],["くも","kumo","mây"],["くるま","kuruma","xe hơi"],
    ["こえ","koe","giọng nói"],["ことば","kotoba","từ ngữ"],["さかな","sakana","con cá"],
    ["さくら","sakura","hoa anh đào"],["しお","shio","muối"],["しま","shima","hòn đảo"],
    ["すし","sushi","sushi"],["たまご","tamago","quả trứng"],["ちから","chikara","sức mạnh"],
    ["つき","tsuki","mặt trăng"],["とけい","tokei","đồng hồ"],["とり","tori","con chim"],
    ["なつ","natsu","mùa hè"],["にく","niku","thịt"],["ねこ","neko","con mèo"],
    ["はな","hana","hoa"],["はる","haru","mùa xuân"],["ひと","hito","con người"],
    ["ふゆ","fuyu","mùa đông"],["ほし","hoshi","ngôi sao"],["まち","machi","thị trấn"],
    ["みず","mizu","nước"],["みみ","mimi","lỗ tai"],["むし","mushi","côn trùng"],
    ["め","me","con mắt"],["やま","yama","núi"],["ゆき","yuki","tuyết"],
    ["よる","yoru","ban đêm"],["わたし","watashi","tôi"],
    ["あたま","atama","đầu"],["あに","ani","anh trai"],["あね","ane","chị gái"],
    ["いもうと","imouto","em gái"],["おとうと","otouto","em trai"],["ちち","chichi","bố"],
    ["はは","haha","mẹ"],["そふ","sofu","ông"],["そぼ","sobo","bà"],
    ["かぞく","kazoku","gia đình"],["ともだち","tomodachi","bạn bè"],["せんせい","sensei","giáo viên"],
    ["がくせい","gakusei","học sinh"],["かいしゃ","kaisha","công ty"],["しごと","shigoto","công việc"],
    ["でんわ","denwa","điện thoại"],["てがみ","tegami","lá thư"],["きっぷ","kippu","vé xe/tàu"],
    ["えいが","eiga","phim điện ảnh"],["おんがく","ongaku","âm nhạc"],["しゃしん","shashin","ảnh chụp"],
    ["にわ","niwa","sân vườn"],["へや","heya","căn phòng"],["まど","mado","cửa sổ"],
    ["とびら","tobira","cánh cửa"],["かぎ","kagi","chìa khóa"],["はし","hashi","đôi đũa"],
    ["さら","sara","cái đĩa"],["ちゃわん","chawan","cái bát cơm"],["たべもの","tabemono","đồ ăn"],
    ["のみもの","nomimono","đồ uống"],["やさい","yasai","rau củ"],["くだもの","kudamono","trái cây"],
    ["にわとり","niwatori","con gà"],["うし","ushi","con bò"],["うま","uma","con ngựa"],
    ["ぶた","buta","con lợn"],["ひつじ","hitsuji","con cừu"],["さる","saru","con khỉ"],
    ["かえる","kaeru","con ếch"],["ちょう","chou","con bướm"],["はち","hachi","con ong"],
    ["くさ","kusa","cỏ"],["こおり","koori","nước đá"],["ゆびわ","yubiwa","nhẫn đeo tay"],
    ["ぼうし","boushi","mũ nón"],["くつした","kutsushita","vớ/tất"],["めがね","megane","kính mắt"],
    ["かばん","kaban","cái cặp"],["つくえ","tsukue","cái bàn học"]
  ]
};

const KATAKANA = {
  gojuon: [
    ["ア","a"],["イ","i"],["ウ","u"],["エ","e"],["オ","o"],
    ["カ","ka"],["キ","ki"],["ク","ku"],["ケ","ke"],["コ","ko"],
    ["サ","sa"],["シ",["shi","si"]],["ス","su"],["セ","se"],["ソ","so"],
    ["タ","ta"],["チ",["chi","ti"]],["ツ",["tsu","tu"]],["テ","te"],["ト","to"],
    ["ナ","na"],["ニ","ni"],["ヌ","nu"],["ネ","ne"],["ノ","no"],
    ["ハ","ha"],["ヒ","hi"],["フ",["fu","hu"]],["ヘ","he"],["ホ","ho"],
    ["マ","ma"],["ミ","mi"],["ム","mu"],["メ","me"],["モ","mo"],
    ["ヤ","ya"],["ユ","yu"],["ヨ","yo"],
    ["ラ","ra"],["リ","ri"],["ル","ru"],["レ","re"],["ロ","ro"],
    ["ワ","wa"],["ヲ",["wo","o"]],
    ["ン","n"]
  ],
  dakuten: [
    ["ガ","ga"],["ギ","gi"],["グ","gu"],["ゲ","ge"],["ゴ","go"],
    ["ザ","za"],["ジ",["ji","zi"]],["ズ","zu"],["ゼ","ze"],["ゾ","zo"],
    ["ダ","da"],["ヂ",["ji","di"]],["ヅ",["zu","du"]],["デ","de"],["ド","do"],
    ["バ","ba"],["ビ","bi"],["ブ","bu"],["ベ","be"],["ボ","bo"],
    ["パ","pa"],["ピ","pi"],["プ","pu"],["ペ","pe"],["ポ","po"]
  ],
  yoon: [
    ["キャ","kya"],["キュ","kyu"],["キョ","kyo"],
    ["シャ",["sha","sya"]],["シュ",["shu","syu"]],["ショ",["sho","syo"]],
    ["チャ",["cha","tya"]],["チュ",["chu","tyu"]],["チョ",["cho","tyo"]],
    ["ニャ","nya"],["ニュ","nyu"],["ニョ","nyo"],
    ["ヒャ","hya"],["ヒュ","hyu"],["ヒョ","hyo"],
    ["ミャ","mya"],["ミュ","myu"],["ミョ","myo"],
    ["リャ","rya"],["リュ","ryu"],["リョ","ryo"],
    ["ギャ","gya"],["ギュ","gyu"],["ギョ","gyo"],
    ["ジャ",["ja","zya"]],["ジュ",["ju","zyu"]],["ジョ",["jo","zyo"]],
    ["ビャ","bya"],["ビュ","byu"],["ビョ","byo"],
    ["ピャ","pya"],["ピュ","pyu"],["ピョ","pyo"]
  ],
  vidu: [
    ["アヒル","ahiru","con vịt"],["ライオン","raion","con sư tử"],["ゾウ","zou","con voi"],
    ["トラ","tora","con hổ"],["キリン","kirin","con hươu cao cổ"],["パンダ","panda","gấu trúc"],
    ["ラクダ","rakuda","con lạc đà"],["コアラ","koara","gấu koala"],["ペンギン","pengin","chim cánh cụt"],
    ["カメラ","kamera","máy ảnh"],["テレビ","terebi","ti vi"],["ラジオ","rajio","đài radio"],
    ["パソコン","pasokon","máy tính cá nhân"],["インターネット",["inta-netto","intaanetto"],"internet"],
    ["ニュース",["nyu-su","nyuusu"],"tin tức"],["スポーツ",["supo-tsu","supootsu"],"thể thao"],
    ["サッカー",["sakka-","sakkaa"],"bóng đá"],["テニス","tenisu","quần vợt"],
    ["ジョギング","jogingu","chạy bộ"],["コーヒー",["ko-hi-","koohii"],"cà phê"],
    ["ジュース",["ju-su","juusu"],"nước ép"],["パン","pan","bánh mì"],
    ["ケーキ",["ke-ki","keeki"],"bánh ngọt"],["チョコレート",["chokore-to","chokoreeto"],"sô-cô-la"],
    ["アイスクリーム",["aisukuri-mu","aisukuriimu"],"kem"],["レストラン","resutoran","nhà hàng"],
    ["ホテル","hoteru","khách sạn"],["タクシー",["takushi-","takushii"],"taxi"],
    ["バス","basu","xe buýt"],["タオル","taoru","khăn tắm"],
    ["シャンプー",["shanpu-","shanpuu"],"dầu gội"],["ソファー",["sofa-","sofaa"],"ghế sofa"],
    ["カレンダー",["karenda-","karendaa"],"lịch"],["ノート",["no-to","nooto"],"quyển vở"],
    ["ペン","pen","cây bút"],["ナイフ","naifu","con dao"],
    ["フォーク",["fo-ku","fooku"],"cái nĩa"],["スプーン",["supu-n","supuun"],"cái thìa"],
    ["ボタン","botan","cái nút"],["カード",["ka-do","kaado"],"thẻ"],
    ["チケット","chiketto","vé"],["パーティー",["pa-ti-","paatii"],"bữa tiệc"],
    ["ダンス","dansu","khiêu vũ"],["ピアノ","piano","đàn piano"],
    ["ギター",["gita-","gitaa"],"đàn guitar"],["メロン","meron","dưa lưới"],
    ["レモン","remon","quả chanh vàng"],["トマト","tomato","cà chua"],
    ["サラダ","sarada","salad"],["ワイン","wain","rượu vang"],
    ["キツネ","kitsune","con cáo"],["ウサギ","usagi","con thỏ"],["シマウマ","shimauma","ngựa vằn"],
    ["サイ","sai","con tê giác"],["ワニ","wani","con cá sấu"],["イルカ","iruka","con cá heo"],
    ["クジラ","kujira","con cá voi"],["ラッコ","rakko","rái cá biển"],["カバ","kaba","hà mã"],
    ["チーター",["chi-ta-","chiitaa"],"báo săn"],["ジャガー",["jaga-","jagaa"],"báo đốm"],
    ["ハムスター",["hamusuta-","hamusutaa"],"chuột hamster"],["モルモット","morumotto","chuột lang"],
    ["オウム","oumu","con vẹt"],["フクロウ","fukurou","cú mèo"],
    ["コンピューター",["konpyu-ta-","konpyuutaa"],"máy vi tính"],["スマートフォン",["suma-tofon","sumaatofon"],"điện thoại thông minh"],
    ["テーブル",["te-buru","teeburu"],"cái bàn"],["ベッド","beddo","giường ngủ"],["カーテン",["ka-ten","kaaten"],"rèm cửa"],
    ["ドア","doa","cửa ra vào"],["マンション","manshon","chung cư cao cấp"],["アパート",["apa-to","apaato"],"nhà chung cư"],
    ["エレベーター",["erebe-ta-","erebeetaa"],"thang máy"],["エスカレーター",["esukare-ta-","esukareetaa"],"thang cuốn"],
    ["デパート",["depa-to","depaato"],"trung tâm thương mại"],["スーパー",["su-pa-","suupaa"],"siêu thị"],
    ["コンビニ","konbini","cửa hàng tiện lợi"],["レジ","reji","quầy thu ngân"],["サイズ","saizu","kích cỡ"],
    ["カラー",["kara-","karaa"],"màu sắc"],["デザイン","dezain","thiết kế"],["アイデア","aidea","ý tưởng"],
    ["プレゼント","purezento","quà tặng"],["クリスマス","kurisumasu","Giáng sinh"],["ハロウィン","harowin","lễ hội Halloween"],
    ["イベント","ibento","sự kiện"],["チーム",["chi-mu","chiimu"],"đội nhóm"],
    ["リーダー",["ri-da-","riidaa"],"người lãnh đạo"],["ゲーム",["ge-mu","geemu"],"trò chơi"],
    ["アニメ","anime","phim hoạt hình"],["マンガ","manga","truyện tranh"],
    ["キャラクター",["kyarakuta-","kyarakutaa"],"nhân vật"],["ロボット","robotto","người máy"],
    ["ミルク","miruku","sữa"],["バター",["bata-","bataa"],"bơ"],["チーズ",["chi-zu","chiizu"],"phô mai"],
    ["ヨーグルト",["yo-guruto","yooguruto"],"sữa chua"],["ハンバーガー",["hanba-ga-","hanbaagaa"],"bánh hamburger"],
    ["ピザ","piza","pizza"]
  ]
};
